stages:
- test
- release

variables:
  ANSIBLE_FORCE_COLOR: 'true'

py-sec-safety:
  stage: test
  image: yourlabs/python
  script: safety check

py-qa:
  stage: test
  image: yourlabs/python
  script: flake8 bigsudo

.test: &test
  stage: test
  image: yourlabs/ansible
  before_script:
  - pip install --upgrade --editable .
  - set -eux

test-playbook-executable:
  <<: *test
  script: |
    ./example/playbook.yml
    grep hello ./playbook.out

test-clone-main:
  <<: *test
  script: |
    bigsudo yourlabs.io/oss/yourlabs.bigsudo-example @localhost example_variable=$(pwd)/test1 -v
    grep main test1

test-clone-update:
  <<: *test
  variables:
  script: |
    bigsudo yourlabs.io/oss/yourlabs.bigsudo-example update --extra-vars="{\"example_variable\": \"$(pwd)/test2\"}" -v
    grep update test2

test-clone-local:
  <<: *test
  script: |
    git clone https://yourlabs.io/oss/yourlabs.bigsudo-example.git /example
    bigsudo /example @localhost example_variable=$(pwd)/test3 -v
    grep main test3
    bigsudo /example @localhost example_variable=$(pwd)/test4 update -v
    grep update test4

pypi:
  stage: release
  image: yourlabs/python
  only: [tags]
  script: pypi-release
